version: "3.8"
services:
  jenkins:
    container_name: aura-jenkins
    user: root
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - docker
  app:
    container_name: aura-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database
      - redis
  database:
    container_name: aura-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=aura
      - POSTGRES_DB=aura-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: aura-redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  jenkins_data:
